from double_linked_list import DoubleLinkedList
inst= DoubleLinkedList()
inst.add_node_at_end(4)
inst.add_node_at_end(3)
inst.add_node_at_end(8)
inst.add_node_at_end(4)
inst.add_node_at_end(1)
inst.add_node_at_end(4)
inst.add_node_at_end(2)
inst.add_node_in_position(3,6)
inst.print_list()
inst.remove_node_by_value(8)
inst.print_list()
inst.get_node_at_value(4)
inst.get_node_at_index(6)
inst.update_node_at_index(2,7)
inst.print_list()
inst.update_node_at_value(4, 3)
inst.print_list()
# inst.sort_asc()
inst.print_list()
inst.has_duplicates_with_information()
# inst.calculate_complexity()